# Settings for ros_control hardware interface
hardware_interface:
   loop_hz: 10 # hz
   joints:
      - joint1
      - joint2

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - joint1
      - joint2
   constraints:
      goal_time: 5.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      joint1:
          trajectory: 0.60
          goal:       0.15
      joint2:
          trajectory: 0.60
          goal:       0.15
   # gains:
   #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

